### PR TITLE
\x01 -> \01

### PR DESCRIPTION
**Pull request by ghost**
because hex escape sequences doesn't have limits on how much
digits a sequence can take and some commands start with letters
that can be a hex digit (for example `ACTION` or `CLIENTINFO`),
`\x01`s can create confusion.

humans while reading the document can recognize `\x01` as a
normal 0x01 ctcp delimiter, but when a person uses a c string like
`\x01CLIENTINFO` on their code, their compiler will think the escape
sequence meant 0x1c, and that person will be puzzled why the
code sends a bad ctcp message.

### CODE REVIEW

**Comment by ghost** [comment]
ping, it's been 1 month @DanielOaks

**Comment by sadiepowell** [comment]
~~This is highly dependent on language. It might be a good idea to use the Unicode printable version of \x01 (i.e. ␁) or the control sequence (i.e. `^A`) in place of an escape code.~~

**Comment by ghost** [comment]
^A might look confusing (if the person doesn't know if 0x01 is ctrl+a) and
i am unsure if unicode chars like that are common in rfcs. tho i can still
modify the patch to use them instead, i have no objection.

**Comment by progval** [comment]
`\x01` is less confusing IMO (but that's probably because I'm a pythonist). Let's just define it properly at the beginning of the spec?

**Comment by ghost** [comment]
hmmmmmm. maybe `%d1`?
defined in ABNF, not confusing, not language dependant.
sounds fine.

hm....
`%d1ACTION waves!%d1`
looks ok in text too.

**Comment by DanielOaks** [comment]
Hmm, the original CTCP spec documents used `\001` which isn't entirely necessary.

I'd be interested in whether there's any guidance on this from e.g. the rfc editor or other recent rfcs, for me the `\x01` reads the easiest (could definitely just be that I've been seeing that for so long, but `\01` doesn't as explicitly read as 'separate' when I'm browsing the examples). I'm not too hot on `%01` or `^A` either to be honest, but out of those two I'd probably prefer `%01` because `%` doesn't really occur in the rest of the text of the examples. Can't use the unicode character because that doesn't render out as utf-8 properly in the txt I-D/RFC exports.

**Comment by ghost** [comment]
well, now i'm confused. we have too much options.
i would go with `\01`. but if we settle on other options
that's fine.

**Comment by DanielOaks** [comment]
For now I'm gonna leave it as-is at `\x01`, but if someone wants to throw a new PR in for `%01` and wants to make the case for changing to use that one instead, I'd consider switching to that option. Thanks for the PR @kemallll, for now I'll close this one and we can discuss more if another PR is submitted.

**Comment by ghost** [comment]
ok, got it. also, a friendly reminder: i actually mentioned
`%d1` not `%01` but hey maybe we can do `%01` too.

**Pull request closed without merging**
